package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/provasign/prism/pkg/kit"
)

// runInit generates MASON.md — the project map a coding agent needs on turn
// one — deterministically from the tree and the code graph. No model call.
func runInit(force bool) int {
	root, err := filepath.Abs(".")
	if err != nil {
		fmt.Fprintln(os.Stderr, "init:", err)
		return 1
	}
	out := filepath.Join(root, "MASON.md")
	if _, err := os.Stat(out); err == nil && !force {
		fmt.Fprintln(os.Stderr, "init: MASON.md already exists — rerun with --force to regenerate")
		return 1
	}
	symbols, edges := 0, 0
	if k, err := kit.Open(root); err == nil {
		if res, err := k.Invoke("prism_index", map[string]any{}); err == nil {
			// kit returns the engine's typed result — normalize through JSON.
			if b, err := json.Marshal(res); err == nil {
				var m map[string]any
				if json.Unmarshal(b, &m) == nil {
					symbols = intOf(m["symbolCount"])
					edges = intOf(m["edgeCount"])
				}
			}
		}
		k.Close()
	}
	md := generateMasonMD(root, symbols, edges)
	if err := os.WriteFile(out, []byte(md), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "init:", err)
		return 1
	}
	fmt.Printf("wrote MASON.md (%d bytes) — loaded into every mason session in this repo; edit freely\n", len(md))
	return 0
}

func intOf(v any) int {
	if f, ok := v.(float64); ok {
		return int(f)
	}
	if n, ok := v.(int); ok {
		return n
	}
	return 0
}

type dirStat struct {
	name  string
	files int
}

// generateMasonMD composes the document from a bounded tree walk plus the
// graph stats. Pure with respect to the filesystem under root — testable.
func generateMasonMD(root string, symbols, edges int) string {
	langCount := map[string]int{}
	dirCount := map[string]int{}
	var entryPoints []string
	totalFiles := 0
	seen := 0
	_ = filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if p != root && strings.HasPrefix(d.Name(), ".") {
				return filepath.SkipDir // hidden trees (.git, .grove, .claude, …) are not project layout
			}
			switch d.Name() {
			case "node_modules", "vendor", "dist", "build", "__pycache__":
				return filepath.SkipDir
			}
			return nil
		}
		seen++
		if seen > 50_000 {
			return filepath.SkipAll
		}
		rel, err := filepath.Rel(root, p)
		if err != nil {
			return nil
		}
		totalFiles++
		if top := strings.SplitN(filepath.ToSlash(rel), "/", 2); len(top) == 2 {
			dirCount[top[0]]++
		}
		if lang := langOf(rel); lang != "" {
			langCount[lang]++
			if ep := entryPointIn(p, rel, lang); ep != "" && len(entryPoints) < 8 {
				entryPoints = append(entryPoints, ep)
			}
		}
		return nil
	})

	name := filepath.Base(root)
	if mod := goModule(root); mod != "" {
		name = mod
	} else if pkg := packageJSONName(root); pkg != "" {
		name = pkg
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — project map for coding agents\n\n", name)
	b.WriteString("_Generated by `mason init` from the tree and the code graph. Edit freely —\nmason loads this file (and AGENTS.md) into every session's system prompt._\n\n")

	fmt.Fprintf(&b, "## Overview\n\n%d files", totalFiles)
	if langs := topLangs(langCount); langs != "" {
		fmt.Fprintf(&b, " · %s", langs)
	}
	if symbols > 0 {
		fmt.Fprintf(&b, " · code graph: %d symbols, %d edges", symbols, edges)
	}
	b.WriteString("\n\n")

	if len(dirCount) > 0 {
		b.WriteString("## Layout\n\n")
		var dirs []dirStat
		for d, n := range dirCount {
			dirs = append(dirs, dirStat{d, n})
		}
		sort.Slice(dirs, func(i, j int) bool { return dirs[i].files > dirs[j].files })
		if len(dirs) > 12 {
			dirs = dirs[:12]
		}
		for _, d := range dirs {
			fmt.Fprintf(&b, "- `%s/` — %d files\n", d.name, d.files)
		}
		b.WriteString("\n")
	}

	if cmds := buildCommands(root); len(cmds) > 0 {
		b.WriteString("## Build & test\n\n")
		for _, c := range cmds {
			fmt.Fprintf(&b, "- `%s`\n", c)
		}
		b.WriteString("\n")
	}

	if len(entryPoints) > 0 {
		b.WriteString("## Entry points\n\n")
		for _, ep := range entryPoints {
			fmt.Fprintf(&b, "- %s\n", ep)
		}
		b.WriteString("\n")
	}

	b.WriteString(`## Conventions

_(fill in: code style, review rules, gotchas an agent should know)_
`)
	return b.String()
}

func langOf(rel string) string {
	switch strings.ToLower(filepath.Ext(rel)) {
	case ".go":
		return "Go"
	case ".py":
		return "Python"
	case ".ts", ".tsx":
		return "TypeScript"
	case ".js", ".jsx":
		return "JavaScript"
	case ".java":
		return "Java"
	case ".rb":
		return "Ruby"
	case ".rs":
		return "Rust"
	case ".cs":
		return "C#"
	case ".c", ".h":
		return "C"
	case ".cpp", ".cc", ".hpp":
		return "C++"
	case ".php":
		return "PHP"
	}
	return ""
}

func topLangs(count map[string]int) string {
	type lc struct {
		l string
		n int
	}
	var ls []lc
	for l, n := range count {
		ls = append(ls, lc{l, n})
	}
	sort.Slice(ls, func(i, j int) bool { return ls[i].n > ls[j].n })
	if len(ls) > 3 {
		ls = ls[:3]
	}
	parts := make([]string, len(ls))
	for i, x := range ls {
		parts[i] = fmt.Sprintf("%s (%d)", x.l, x.n)
	}
	return strings.Join(parts, ", ")
}

// entryPointIn detects a program entry in one file (bounded read).
func entryPointIn(abs, rel, lang string) string {
	if strings.Contains(rel, "_test.") || strings.HasPrefix(rel, "test") {
		return ""
	}
	b, err := os.ReadFile(abs)
	if err != nil || len(b) > 512_000 {
		return ""
	}
	src := string(b)
	switch lang {
	case "Go":
		// Line-anchored: a mid-line mention of the string (e.g. in a
		// detector like this one) must not read as an entry point.
		if goMainRe.MatchString(src) && strings.Contains(src, "package main") {
			return "`" + rel + "` — `func main`"
		}
	case "Python":
		if strings.Contains(src, `if __name__ == "__main__"`) || strings.Contains(src, "if __name__ == '__main__'") {
			return "`" + rel + "` — `__main__` guard"
		}
	}
	return ""
}

var goMainRe = regexp.MustCompile(`(?m)^func main\(`)

func goModule(root string) string {
	b, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(b), "\n") {
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}

func packageJSONName(root string) string {
	b, err := os.ReadFile(filepath.Join(root, "package.json"))
	if err != nil {
		return ""
	}
	// cheap extraction; a full parse is overkill for one string field
	for _, line := range strings.Split(string(b), "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, `"name"`) {
			if parts := strings.SplitN(t, ":", 2); len(parts) == 2 {
				return strings.Trim(strings.TrimSuffix(strings.TrimSpace(parts[1]), ","), `"`)
			}
		}
	}
	return ""
}

// buildCommands detects how this project builds and tests, by ecosystem.
func buildCommands(root string) []string {
	var out []string
	exists := func(name string) bool {
		_, err := os.Stat(filepath.Join(root, name))
		return err == nil
	}
	if exists("go.mod") {
		out = append(out, "go build ./...", "go test ./...")
	}
	if exists("package.json") {
		b, _ := os.ReadFile(filepath.Join(root, "package.json"))
		for _, script := range []string{"build", "test", "lint"} {
			if strings.Contains(string(b), `"`+script+`"`) {
				out = append(out, "npm run "+script)
			}
		}
	}
	if exists("Cargo.toml") {
		out = append(out, "cargo build", "cargo test")
	}
	if exists("pyproject.toml") || exists("pytest.ini") || exists("setup.py") {
		out = append(out, "pytest")
	}
	if exists("Makefile") {
		out = append(out, "make  (see Makefile targets)")
	}
	return out
}
